import 'server-only'

import { randomBytes } from 'node:crypto'
import { mkdir, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'

import sharp from 'sharp'

import { AppError, MESSAGES, errors } from './errors'
import { toPersianDigits } from './persian'

/**
 * Image uploads. §16 / §72 / §76.
 *
 * ── The security model ─────────────────────────────────────────────────────
 * A declared MIME type and a file extension are both attacker-controlled and
 * prove nothing. The only check that means anything is DECODING the file: a
 * polyglot that claims to be a PNG but carries a PHP payload fails to parse as
 * an image, and re-encoding the pixels discards everything that was not pixels
 * — EXIF, trailing archives, embedded scripts.
 *
 * Files are written outside the webroot with random names and served through a
 * route handler with a fixed Content-Type, so nothing here can ever be
 * executed by the web server, whatever it is named.
 */

const MAX_BYTES = 8 * 1024 * 1024
const MAX_DIMENSION = 6000
const MIN_DIMENSION = 200

/** Formats we are willing to DECODE. Output is always AVIF/WebP/JPEG. */
const ACCEPTED_FORMATS = new Set(['jpeg', 'png', 'webp', 'avif'])

import { IMAGE_WIDTHS, renditionPaths } from './media-url'

export type ImageVariant = 'avif' | 'webp' | 'jpeg'

export function uploadRoot(): string {
  return path.resolve(process.env.UPLOAD_DIR ?? './storage')
}

/**
 * Resolves a stored relative path to an absolute one, refusing anything that
 * escapes the upload root.
 *
 * Stored paths are generated by us, not supplied by users — but this is the
 * function the media route handler calls with a URL segment, so it is the
 * boundary where path traversal has to die.
 */
export function resolveStoredPath(relative: string): string {
  const root = uploadRoot()
  const resolved = path.resolve(root, relative)

  if (resolved !== root && !resolved.startsWith(root + path.sep)) {
    throw errors.forbidden('مسیر فایل معتبر نیست.')
  }
  return resolved
}

function randomName(): string {
  // Random rather than derived from the original filename: a user-supplied
  // name is a needless injection surface and leaks information.
  return randomBytes(16).toString('hex')
}

export interface ProcessedImage {
  /** Relative path of the primary (largest WebP) rendition. */
  path: string
  width: number
  height: number
  /** Every file written, for cleanup if the surrounding transaction fails. */
  files: string[]
}

export interface UploadOptions {
  /** Subdirectory under the upload root, e.g. "products" or "categories". */
  folder: 'products' | 'categories' | 'blog' | 'brand' | 'homepage'
  /** Skip responsive derivatives — used for logos and favicons. */
  singleSize?: boolean
}

/**
 * Validates, re-encodes and stores an uploaded image.
 * Throws an AppError with a Persian message on any rejection.
 */
export async function processUpload(
  file: File,
  options: UploadOptions,
): Promise<ProcessedImage> {
  if (file.size > MAX_BYTES) {
    throw new AppError('VALIDATION', MESSAGES.fileTooLarge)
  }
  if (file.size === 0) {
    throw new AppError('VALIDATION', MESSAGES.fileCorrupt)
  }

  const buffer = Buffer.from(await file.arrayBuffer())

  // THE check. Everything before this was advisory.
  let image: sharp.Sharp
  let metadata: sharp.Metadata
  try {
    image = sharp(buffer, { failOn: 'error' })
    metadata = await image.metadata()
  } catch {
    throw new AppError('VALIDATION', MESSAGES.fileCorrupt)
  }

  if (!metadata.format || !ACCEPTED_FORMATS.has(metadata.format)) {
    throw new AppError('VALIDATION', MESSAGES.fileTypeInvalid)
  }

  const width = metadata.width ?? 0
  const height = metadata.height ?? 0

  if (width < MIN_DIMENSION || height < MIN_DIMENSION) {
    throw new AppError(
      'VALIDATION',
      `ابعاد تصویر باید حداقل ${toPersianDigits(MIN_DIMENSION)}×${toPersianDigits(MIN_DIMENSION)} پیکسل باشد.`,
    )
  }
  if (width > MAX_DIMENSION || height > MAX_DIMENSION) {
    throw new AppError(
      'VALIDATION',
      `ابعاد تصویر نباید بیش از ${toPersianDigits(MAX_DIMENSION)}×${toPersianDigits(MAX_DIMENSION)} پیکسل باشد.`,
    )
  }

  const name = randomName()
  const dir = path.join(uploadRoot(), options.folder)
  await mkdir(dir, { recursive: true })

  const written: string[] = []

  // Only widths the source can actually fill — we never upscale, so emitting a
  // "1920w" descriptor for a 900px source would lie to the browser's selection.
  const fitting = IMAGE_WIDTHS.filter((w) => w <= width)
  const widths: number[] = options.singleSize
    ? [Math.min(width, 1280)]
    : fitting.length > 0
      ? [...fitting]
      : [width] // source smaller than our smallest step

  try {
    for (const targetWidth of widths) {
      // `rotate()` with no argument applies the EXIF orientation and then
      // drops the metadata — without it, phone photos come out sideways.
      const base = sharp(buffer, { failOn: 'error' })
        .rotate()
        .resize({ width: targetWidth, withoutEnlargement: true })

      const avif = await base.clone().avif({ quality: 55, effort: 4 }).toBuffer()
      const webp = await base.clone().webp({ quality: 78 }).toBuffer()

      const avifRel = path.posix.join(options.folder, `${name}-${targetWidth}.avif`)
      const webpRel = path.posix.join(options.folder, `${name}-${targetWidth}.webp`)

      await writeFile(path.join(uploadRoot(), avifRel), avif)
      written.push(avifRel)
      await writeFile(path.join(uploadRoot(), webpRel), webp)
      written.push(webpRel)
    }

    // A JPEG fallback for anything that cannot take WebP or AVIF.
    const jpegRel = path.posix.join(options.folder, `${name}.jpg`)
    const jpeg = await sharp(buffer, { failOn: 'error' })
      .rotate()
      .resize({ width: Math.min(width, 1280), withoutEnlargement: true })
      .jpeg({ quality: 82, mozjpeg: true })
      .toBuffer()
    await writeFile(path.join(uploadRoot(), jpegRel), jpeg)
    written.push(jpegRel)

    const primaryWidth = widths[widths.length - 1] ?? width
    const scale = Math.min(1, primaryWidth / width)

    return {
      path: path.posix.join(options.folder, `${name}-${primaryWidth}.webp`),
      width: Math.round(width * scale),
      height: Math.round(height * scale),
      files: written,
    }
  } catch (error) {
    // Do not leave half-written derivatives behind on failure.
    await Promise.all(written.map((rel) => deleteStored(rel).catch(() => {})))
    throw error instanceof AppError ? error : new AppError('VALIDATION', MESSAGES.fileCorrupt)
  }
}

export async function deleteStored(relative: string): Promise<void> {
  try {
    await unlink(resolveStoredPath(relative))
  } catch (error) {
    // Already gone is a success for our purposes.
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
}

/** Removes every rendition of an image, given the stored primary path. */
export async function deleteImageSet(primaryPath: string): Promise<void> {
  // Rendition naming lives in one place — media-url.ts — so the delete path
  // and the srcset path can never disagree about which files exist.
  await Promise.all(renditionPaths(primaryPath).map((p) => deleteStored(p).catch(() => {})))
}

/* ── URL helpers ───────────────────────────────────────────────────────── */

/**
 * Re-exported from lib/media-url.ts so server code has one import site.
 * They live there because client components need them too, and this module is
 * `server-only`.
 */
export {
  IMAGE_WIDTHS,
  buildSrcSet,
  contentTypeFor,
  jpegFallbackUrl,
  mediaUrl,
} from './media-url'
