import 'server-only'

import { getJson } from '@/lib/settings'
import { contentStyleClass, type ContentStyle } from '@/lib/content-style'

export const COPY_CATALOG = {
  'home.hero.title': 'ظرافت، در هر جزئیات',
  'home.hero.cta': 'مشاهده همه محصولات',
  'home.featured.eyebrow': 'محصولات منتخب',
  'home.featured.title': 'محصولات منتخب',
  'home.featured.cta': 'مشاهده همه',
  'home.new.eyebrow': 'جدیدترین‌ها',
  'home.new.title': 'جدیدترین‌ها',
  'home.new.cta': 'همه محصولات',
  'home.best.eyebrow': 'پرفروش‌ترین‌ها',
  'home.best.title': 'انتخاب مشتریان',
  'home.best.cta': 'همه محصولات',
  'home.categories.title': 'خرید بر اساس دسته',
  'home.promo.title': 'ارسال محرمانه به سراسر ایران',
  'home.promo.cta': 'مشاهده',
  'home.story.cta': 'بیشتر بخوانید',
  'home.blog.title': 'خواندنی‌ها',
  'home.blog.cta': 'همه نوشته‌ها',
  'about.eyebrow': 'معرفی برند',
  'about.storyTitle': 'داستان ما',
  'about.promiseEyebrow': 'قول ما به شما',
  'about.promiseTitle': 'چیزی که در هر سفارش تکرار می‌شود',
  'contact.eyebrow': 'پشتیبانی و مشاوره',
  'contact.channelsEyebrow': 'راه‌های ارتباطی',
  'contact.channelsTitle': 'از هر کدام راحت‌ترید',
  'contact.orderTitle': 'سفارشی در جریان دارید؟',
  'contact.orderBody': 'وضعیت لحظه‌ای سفارش‌ها، کد رهگیری و فاکتورها در حساب کاربری شما در دسترس است.',
  'contact.orderCta': 'پیگیری سفارش',
  'contact.channelsAction': 'از هر کدام راحت‌ترید',
  'auth.login.title': 'ورود به حساب',
  'auth.login.subtitle': 'با رمز عبور یا کد یک‌بار مصرف وارد شوید.',
  'auth.register.title': 'ساخت حساب کاربری',
  'auth.register.subtitle': 'برای ثبت سفارش و پیگیری آن، یک حساب بسازید.',
  'auth.forgot.title': 'بازیابی رمز عبور',
  'cart.empty.title': 'سبد خرید شما خالی است',
  'cart.title': 'سبد خرید',
  'cart.empty.description': 'محصولات مورد علاقه خود را به سبد اضافه کنید.',
  'cart.start': 'شروع خرید',
  'cart.issues.title': 'برخی اقلام نیاز به بررسی دارند',
  'cart.issues.body': 'موجودی یا وضعیت بعضی محصولات تغییر کرده است. پیش از ادامه، آن‌ها را اصلاح یا حذف کنید.',
  'cart.summary': 'خلاصه سفارش',
  'cart.items': 'جمع کالاها',
  'cart.discount': 'تخفیف',
  'cart.shipping': 'هزینه ارسال',
  'cart.free': 'رایگان',
  'cart.total': 'مبلغ قابل پرداخت',
  'cart.continue': 'ادامه و تسویه حساب',
  'cart.loginContinue': 'ورود و تسویه حساب',
  'cart.back': 'ادامه خرید',
  'checkout.empty.title': 'سبد خرید شما خالی است',
  'checkout.unavailable.title': 'در حال حاضر امکان ثبت سفارش وجود ندارد',
  'account.orders.empty': 'هنوز سفارشی ثبت نکرده‌اید',
  'account.wishlist.empty': 'فهرست علاقه‌مندی‌ها خالی است',
  'account.wishlist.title': 'علاقه‌مندی‌ها',
  'account.wishlist.description': 'محصولی که می‌پسندید را با زدن نشان قلب ذخیره کنید تا بعداً راحت پیدایش کنید.',
  'account.orders.title': 'سفارش‌های من',
  'account.orders.start': 'شروع خرید',
  'reviews.pending': 'در انتظار تأیید',
  'reviews.published': 'منتشر شده',
  'reviews.rejected': 'تأیید نشد',
  'reviews.hidden': 'پنهان شده',
  'auth.forgot.description': 'کد تأیید برای شما پیامک می‌شود، سپس رمز جدید را انتخاب کنید.',
  'site.skipContent': 'پرش به محتوای اصلی',
  'meta.defaultTitle': 'فروشگاه لباس زیر زنانه',
  'meta.defaultDescription': 'فروشگاه اینترنتی ارکید؛ لباس زیر زنانه با کیفیت، طراحی ظریف و ارسال محرمانه به سراسر ایران.',
  'meta.notFound': 'صفحه یافت نشد',
  'meta.productNotFound': 'محصول یافت نشد',
  'meta.categoryNotFound': 'دسته‌بندی یافت نشد',
  'meta.postNotFound': 'نوشته یافت نشد',
  'search.empty.title': 'نتیجه‌ای یافت نشد',
  'product.added': 'به سبد خرید اضافه شد.',
  'product.payLaterAdded': 'به سبد پرداخت بعدی اضافه شد.',
  'product.variantUnavailable': 'ترکیب انتخاب‌شده موجود نیست',
  'product.unavailable': 'ناموجود',
  'product.inStock': 'موجود در انبار',
  'product.adding': 'در حال افزودن…',
  'product.addToCart': 'افزودن به سبد خرید',
  'product.addToPayLater': 'افزودن به سبد پرداخت بعدی',
  'product.sku': 'کد کالا',
  'auth.phone': 'شماره موبایل',
  'auth.showPassword': 'نمایش رمز عبور',
  'auth.hidePassword': 'پنهان کردن رمز عبور',
  'auth.otp': 'کد تأیید',
  'auth.sentPrefix': 'کد تأیید به شماره',
  'auth.sentSuffix': 'پیامک شد.',
  'auth.editPhone': 'تغییر شماره',
  'auth.resendPrefix': 'ارسال مجدد کد تا',
  'auth.resendSuffix': 'ثانیه دیگر',
  'auth.resend': 'ارسال مجدد کد',
  'search.label': 'جستجو در محصولات',
  'search.placeholder': 'جستجو در محصولات…',
  'account.logout': 'خروج از حساب',
  'account.loggingOut': 'در حال خروج…',
  'payment.referenceLabel': 'کد رهگیری / شماره پیگیری پرداخت',
  'payment.referenceHint': 'این کد را در پیامک بانک یا تاریخچه تراکنش‌های اپلیکیشن بانکی خود پیدا می‌کنید.',
  'payment.submitting': 'در حال ثبت…',
  'payment.submit': 'ثبت پرداخت',
  'checkout.savedAddresses': 'انتخاب از نشانی‌های ذخیره‌شده',
  'checkout.newAddress': 'نشانی جدید',
  'checkout.recipient': 'اطلاعات گیرنده',
  'checkout.fullName': 'نام و نام خانوادگی',
  'checkout.mobile': 'شماره موبایل',
  'checkout.province': 'استان',
  'checkout.select': 'انتخاب کنید',
  'checkout.city': 'شهر',
  'checkout.address': 'نشانی کامل',
  'checkout.addressPlaceholder': 'خیابان، کوچه، پلاک، واحد',
  'checkout.postalCode': 'کد پستی',
  'checkout.postalHint': 'کد پستی ۱۰ رقمی، بدون خط تیره',
  'checkout.note': 'توضیحات سفارش (اختیاری)',
  'checkout.notePlaceholder': 'مثلاً ساعت مناسب تحویل',
  'checkout.shippingMethod': 'روش ارسال',
  'checkout.paymentMethod': 'روش پرداخت',
  'checkout.placing': 'در حال ثبت سفارش…',
  'checkout.place': 'ثبت سفارش و ادامه',
  'checkout.shippingCostPrefix': 'هزینه ارسال:',
  'checkout.freeEligible': 'برای خریدهای واجد شرایط رایگان',
  'checkout.title': 'تسویه حساب',
  'checkout.emptyDescription': 'پیش از تسویه حساب، محصولی به سبد خرید اضافه کنید.',
  'checkout.noPayments': 'هیچ روش پرداختی فعال نیست. لطفاً بعداً تلاش کنید یا با پشتیبانی تماس بگیرید.',
  'checkout.backCart': 'بازگشت به سبد خرید',
  'checkout.noShipping': 'روش ارسالی فعال نیست',
  'checkout.contactSupport': 'لطفاً با پشتیبانی تماس بگیرید.',
  'checkout.yourOrder': 'سفارش شما',
  'checkout.quantity': 'تعداد',
  'account.nav.dashboard': 'پیشخوان',
  'account.nav.orders': 'سفارش‌ها',
  'account.nav.payLater': 'پرداخت بعدی',
  'account.nav.wishlist': 'علاقه‌مندی‌ها',
  'account.nav.addresses': 'نشانی‌ها',
  'account.nav.reviews': 'دیدگاه‌ها',
  'account.nav.profile': 'اطلاعات حساب',
  'account.nav.aria': 'ناوبری حساب کاربری',
  'account.eyebrow': 'حساب کاربری',
  'account.hello': 'سلام',
  'account.payLater': 'سبد پرداخت بعدی',
  'account.awaitingPayment': 'در انتظار پرداخت',
  'account.waitingDecision': 'منتظر تصمیم شما',
  'account.noActiveCart': 'سبد فعالی ندارید',
  'account.notRegistered': 'هنوز ثبت نشده',
  'account.recentOrders': 'آخرین سفارش‌ها',
  'account.viewAll': 'مشاهده همه',
  'account.emptyOrdersDescription': 'پس از اولین خرید، سفارش‌های شما اینجا نمایش داده می‌شود.',
  'account.item': 'کالا',
  'account.defaultUser': 'کاربر ارکید',
  'addresses.title': 'نشانی‌ها',
  'addresses.description': 'نشانی‌های ذخیره‌شده هنگام تسویه حساب در دسترس شماست. نشانی پیش‌فرض به‌صورت خودکار انتخاب می‌شود.',
  'addresses.empty': 'هنوز نشانی ثبت نکرده‌اید',
  'addresses.emptyDescription': 'با ثبت نشانی، تسویه حساب در سفارش‌های بعدی سریع‌تر انجام می‌شود.',
  'reviews.mine': 'دیدگاه‌های من',
  'reviews.empty': 'هنوز دیدگاهی ثبت نکرده‌اید',
  'reviews.emptyDescription': 'پس از خرید، تجربه خود را با دیگران به اشتراک بگذارید.',
  'reviews.edit': 'ویرایش دیدگاه',
  'profile.title': 'اطلاعات حساب',
  'profile.memberSince': 'عضو ارکید از',
  'search.title': 'جستجو',
  'search.enterTitle': 'عبارتی برای جستجو وارد کنید',
  'search.enterDescription': 'نام محصول، دسته‌بندی یا ویژگی مورد نظر خود را بنویسید.',
  'search.results': 'نتایج جستجو',
  'search.foundSuffix': 'محصول یافت شد',
  'search.emptyDescription': 'عبارت دیگری را امتحان کنید یا از دسته‌بندی‌ها استفاده کنید.',
  'search.viewAll': 'مشاهده همه محصولات',
  'error.title': 'خطایی رخ داد',
  'error.description': 'متأسفانه در نمایش این صفحه مشکلی پیش آمد. لطفاً دوباره تلاش کنید.',
  'error.retry': 'تلاش دوباره',
  'error.home': 'صفحه اصلی',
  'error.trackingCode': 'کد پیگیری',
  'notFound.title': 'صفحه مورد نظر یافت نشد',
  'notFound.description': 'ممکن است نشانی را اشتباه وارد کرده باشید یا این صفحه دیگر در دسترس نباشد.',
  'notFound.home': 'بازگشت به صفحه اصلی',
  'notFound.search': 'جستجوی محصولات',
  'gateway.connecting': 'در حال اتصال به درگاه…',
  'gateway.paid': 'پرداخت با موفقیت تأیید شد.',
  'gateway.notPaid': 'پرداخت هنوز از سوی درگاه تأیید نشده است.',
  'gateway.checking': 'در حال بررسی…',
  'gateway.check': 'بررسی وضعیت پرداخت',
  'wishlist.removePrefix': 'حذف',
  'wishlist.addPrefix': 'افزودن',
  'wishlist.fromSuffix': 'از علاقه‌مندی‌ها',
  'wishlist.toSuffix': 'به علاقه‌مندی‌ها',
  'rail.previousPrefix': 'قبلی در',
  'rail.nextPrefix': 'بعدی در',
  'common.home': 'خانه',
  'catalog.products': 'همه محصولات',
  'catalog.eyebrow': 'مجموعه کامل',
  'catalog.description': 'همه چیزهایی که در ارکید موجود است، بدون دسته‌بندی. با رنگ، سایز و موجودی فیلتر کنید.',
  'catalog.productSuffix': 'محصول',
  'catalog.empty': 'محصولی یافت نشد',
  'catalog.emptyDescription': 'با فیلترهای انتخاب‌شده محصولی موجود نیست. فیلترها را تغییر دهید.',
  'catalog.clearFilters': 'حذف فیلترها',
  'product.description': 'توضیحات محصول',
  'product.related': 'محصولات مرتبط',
  'product.optionUnavailable': 'ناموجود',
  'product.currentCombinationUnavailable': 'این ترکیب در حال حاضر موجود نیست.',
  'product.onlyPrefix': 'تنها',
  'product.remainingSuffix': 'عدد باقی مانده است.',
  'product.add': 'افزودن',
  'product.imagesAria': 'تصاویر محصول',
  'blog.title': 'مجله ارکید',
  'blog.heading': 'خواندنی‌ها',
  'blog.description': 'راهنمای انتخاب سایز، نکات نگهداری و آنچه پیش از خرید خوب است بدانید.',
  'blog.empty': 'هنوز نوشته‌ای منتشر نشده است',
  'blog.breadcrumb': 'مجله',
  'auth.checking': 'در حال بررسی…',
  'auth.login': 'ورود',
  'auth.password': 'رمز عبور',
  'auth.forgotPassword': 'رمز عبور را فراموش کرده‌اید؟',
  'auth.loggingIn': 'در حال ورود…',
  'auth.sending': 'در حال ارسال…',
  'auth.sendOtp': 'ارسال کد تأیید',
  'auth.noAccount': 'حساب کاربری ندارید؟',
  'auth.registerLink': 'ثبت‌نام کنید',
  'auth.otpMode': 'کد یک‌بار مصرف',
  'auth.loginMethod': 'روش ورود',
  'auth.confirmCreate': 'تأیید و ساخت حساب',
  'auth.fullName': 'نام و نام خانوادگی',
  'auth.fullNamePlaceholder': 'مثلاً شیرین محمدی',
  'auth.passwordHint': 'حداقل ۸ کاراکتر.',
  'auth.continue': 'ادامه',
  'auth.newPassword': 'رمز عبور جدید',
  'auth.saving': 'در حال ذخیره…',
  'auth.resetAndLogin': 'تغییر رمز عبور و ورود',
  'auth.sendRecovery': 'ارسال کد بازیابی',
  'auth.remembered': 'رمز عبور را به یاد آوردید؟',
  'auth.backToLogin': 'بازگشت به ورود',
  'common.backToShop': 'بازگشت به فروشگاه',
  'common.viewProducts': 'مشاهده محصولات',
  'common.contactUs': 'تماس با ما',
  'common.cancel': 'انصراف',
  'common.close': 'بستن',
  'common.previous': 'قبلی',
  'common.next': 'بعدی',
  'common.free': 'رایگان',
  'common.save': 'ذخیره',
  'common.saving': 'در حال ذخیره…',
  'common.delete': 'حذف',
  'common.deleting': 'در حال حذف…',
  'common.edit': 'ویرایش',
  'common.optional': 'اختیاری',
  'header.blog': 'مجله',
  'header.account': 'حساب کاربری',
  'header.login': 'ورود به حساب',
  'header.wishlist': 'علاقه‌مندی‌ها',
  'header.cart': 'سبد خرید',
  'header.mainNav': 'ناوبری اصلی',
  'header.homeAria': 'صفحه اصلی',
  'mobile.menu': 'منوی اصلی',
  'mobile.openMenu': 'باز کردن منو',
  'mobile.closeMenu': 'بستن منو',
  'mobile.accountDescription': 'مشاهده حساب و سفارش‌ها',
  'mobile.welcome': 'به ارکید خوش آمدید',
  'mobile.welcomeDescription': 'برای ثبت سفارش و ذخیره علاقه‌مندی‌ها وارد شوید.',
  'mobile.login': 'ورود',
  'mobile.register': 'ثبت‌نام',
  'mobile.categories': 'دسته‌بندی‌ها',
  'mobile.more': 'بیشتر',
  'mobile.orders': 'سفارش‌ها',
  'mobile.logoAlt': 'ارکید',
  'mobile.shipping': 'شیوه ارسال',
  'footer.tracking': 'پیگیری سفارش',
  'footer.trust': 'نماد اعتماد',
  'footer.rights': 'تمامی حقوق محفوظ است.',
  'footer.instagram': 'اینستاگرام',
  'footer.telegram': 'تلگرام',
  'footer.whatsapp': 'واتس‌اپ',
  'filters.title': 'فیلترها',
  'filters.color': 'رنگ',
  'filters.size': 'سایز',
  'filters.stock': 'موجودی',
  'filters.priceRange': 'محدوده قیمت',
  'filters.to': 'تا',
  'filters.currency': 'تومان',
  'filters.clear': 'حذف فیلترها',
  'filters.availableOnly': 'فقط کالاهای موجود',
  'filters.sort': 'مرتب‌سازی',
  'filters.newest': 'جدیدترین',
  'filters.cheapest': 'ارزان‌ترین',
  'filters.expensive': 'گران‌ترین',
  'filters.popular': 'پرفروش‌ترین',
  'product.new': 'تازه رسیده',
  'product.outOfStock': 'فعلاً ناموجود',
  'product.previousPrice': 'قیمت پیشین',
  'product.discountSuffix': 'درصد تخفیف',
  'product.ratingPrefix': 'امتیاز',
  'common.breadcrumb': 'مسیر صفحه',
  'common.pagination': 'صفحه‌بندی',
  'common.page': 'صفحه',
  'blog.metaDescription': 'راهنمای انتخاب سایز، نگهداری لباس زیر و مطالب خواندنی درباره پوشاک زنانه.',
  'cart.removePrefix': 'حذف',
  'cart.removeSuffix': 'از سبد خرید',
  'cart.noLongerAvailable': 'این محصول دیگر در دسترس نیست.',
  'cart.onlyPrefix': 'تنها',
  'cart.onlySuffix': 'عدد موجود است.',
  'cart.decrease': 'کاهش تعداد',
  'cart.increase': 'افزایش تعداد',
  'auth.termsPrefix': 'با ثبت‌نام،',
  'auth.terms': 'قوانین و مقررات',
  'auth.and': 'و',
  'auth.privacy': 'حریم خصوصی',
  'auth.termsSuffix': 'ارکید را می‌پذیرید.',
  'auth.alreadyRegistered': 'قبلاً ثبت‌نام کرده‌اید؟',
  'auth.loginLink': 'وارد شوید',
  'auth.stepDetails': 'مشخصات',
  'auth.stepVerify': 'تأیید شماره',
  'auth.stepAriaPrefix': 'مرحله',
  'address.default': 'پیش‌فرض',
  'address.postalCode': 'کد پستی',
  'address.note': 'یادداشت',
  'address.deleteConfirm': 'این نشانی حذف شود؟',
  'address.add': 'افزودن نشانی',
  'address.editTitle': 'ویرایش نشانی',
  'address.newTitle': 'نشانی جدید',
  'address.recipient': 'نام گیرنده',
  'address.phone': 'شماره تماس گیرنده',
  'address.province': 'استان',
  'address.city': 'شهر',
  'address.full': 'نشانی کامل',
  'address.courierNote': 'یادداشت برای پیک',
  'address.notePlaceholder': 'مثلاً زنگ واحد ۳',
  'address.makeDefault': 'نشانی پیش‌فرض من باشد',
  'address.save': 'ذخیره نشانی',
  'profile.personal': 'اطلاعات شخصی',
  'profile.email': 'ایمیل',
  'profile.mobileIdentity': 'شماره موبایل شناسه حساب شماست. برای تغییر آن با پشتیبانی تماس بگیرید.',
  'profile.saved': 'اطلاعات شما ذخیره شد.',
  'profile.saveChanges': 'ذخیره تغییرات',
  'profile.changePassword': 'تغییر رمز عبور',
  'profile.choosePassword': 'انتخاب رمز عبور',
  'profile.noPassword': 'حساب شما هنوز رمز عبور ندارد. با انتخاب رمز، می‌توانید بدون کد پیامکی هم وارد شوید.',
  'profile.currentPassword': 'رمز عبور فعلی',
  'profile.passwordChanged': 'رمز عبور تغییر کرد. سایر دستگاه‌ها از حساب خارج شدند.',
  'profile.setPassword': 'ثبت رمز عبور',
  'reviews.customers': 'نظر مشتریان',
  'reviews.title': 'دیدگاه‌ها',
  'reviews.editMine': 'ویرایش دیدگاه من',
  'reviews.submit': 'ثبت دیدگاه',
  'reviews.login': 'برای ثبت دیدگاه وارد شوید',
  'reviews.success': 'دیدگاه شما ثبت شد و پس از بررسی و تأیید نمایش داده می‌شود.',
  'reviews.none': 'هنوز دیدگاهی ثبت نشده است. اولین نفری باشید که نظر می‌دهد.',
  'reviews.verified': 'خرید تأییدشده',
  'reviews.replyPrefix': 'پاسخ ارکید',
  'reviews.rating': 'امتیاز شما',
  'reviews.subject': 'عنوان',
  'reviews.body': 'متن دیدگاه',
  'reviews.placeholder': 'تجربه خود را از این محصول بنویسید…',
  'reviews.moderation': 'دیدگاه شما پس از بررسی توسط تیم ارکید منتشر می‌شود.',
  'reviews.updating': 'به‌روزرسانی دیدگاه',
  'sizeGuide.close': 'بستن',
  'sizeGuide.missing': 'تصویر راهنما هنوز بارگذاری نشده است. برای دیدن جدول اندازه‌ها صفحهٔ راهنما را باز کنید.',
  'sizeGuide.full': 'راهنمای کامل اندازه‌گیری',
  'order.details': 'جزئیات سفارش',
  'order.mine': 'سفارش‌های من',
  'order.prefix': 'سفارش',
  'order.trackingSaved': 'کد رهگیری ثبت شد',
  'order.trackingPending': 'پرداخت شما در انتظار بررسی است. پس از تأیید، وضعیت سفارش به‌روزرسانی می‌شود و برای شما پیامک ارسال خواهد شد.',
  'order.paymentConfirmed': 'پرداخت تأیید شد',
  'order.paymentConfirmedBody': 'تراکنش از درگاه استعلام شد و سفارش شما با موفقیت پرداخت شد.',
  'order.paymentNotConfirmed': 'پرداخت هنوز تأیید نشده است',
  'order.paymentNotConfirmedBody': 'اگر مبلغ از حساب شما کسر شده، وضعیت را دوباره بررسی کنید و از ایجاد پرداخت تازه خودداری کنید.',
  'order.paymentRejected': 'پرداخت تأیید نشد',
  'order.paymentRejectedBody': 'کد رهگیری ثبت‌شده تأیید نشد. لطفاً دوباره تلاش کنید.',
  'order.awaitingPayment': 'این سفارش در انتظار پرداخت است.',
  'order.continuePayment': 'ادامه پرداخت',
  'order.pay': 'پرداخت سفارش',
  'order.items': 'اقلام سفارش',
  'order.itemsTotal': 'جمع کالاها',
  'order.discount': 'تخفیف',
  'order.shippingCost': 'هزینه ارسال',
  'order.shippingMethod': 'روش ارسال',
  'order.total': 'مبلغ کل',
  'order.deliveryAddress': 'نشانی تحویل',
  'order.shippingCompany': 'شرکت حمل',
  'order.shipmentTracking': 'کد رهگیری مرسوله',
  'order.customerNote': 'یادداشت شما',
  'order.paymentStatus': 'وضعیت پرداخت',
  'order.paymentMethod': 'روش پرداخت',
  'order.status': 'وضعیت',
  'order.trackingCode': 'کد رهگیری',
  'order.confirmedAt': 'تاریخ تأیید',
  'order.cardToCard': 'کارت به کارت',
  'order.torobPay': 'ترب‌پی',
  'order.bitPay': 'بیت‌پی',
  'order.amountDue': 'مبلغ قابل پرداخت',
  'order.backDetails': 'بازگشت به جزئیات سفارش',
  'order.accountInfo': 'اطلاعات حساب',
  'order.bank': 'بانک',
  'order.cardNumber': 'شماره کارت',
  'order.accountHolder': 'به نام',
  'order.submitTracking': 'ثبت کد رهگیری',
  'order.viewDetails': 'مشاهده جزئیات سفارش',
  'order.gatewayNotice': 'پس از انتقال به درگاه، نتیجه پرداخت فقط با استعلام مستقیم از سرویس پرداخت تأیید می‌شود. اگر پاسخ درگاه قطع شد، پرداخت تازه‌ای ایجاد نکنید و از صفحه سفارش وضعیت را بررسی کنید.',
  'order.previousRejected': 'پرداخت قبلی تأیید نشد',
  'order.invalidTracking': 'کد رهگیری ثبت‌شده تأیید نشد. لطفاً کد صحیح را دوباره وارد کنید.',
  'order.trackingInstructions': 'پس از واریز مبلغ، کد رهگیری یا شماره پیگیری تراکنش را وارد کنید. سفارش شما پس از بررسی و تأیید توسط تیم ارکید پردازش می‌شود.',
  'order.createdAt': 'ثبت سفارش',
  'faq.eyebrow': 'راهنمای خرید',
  'faq.description': 'پرتکرارترین پرسش‌های مشتریان درباره سایز، سفارش، ارسال و بازگشت کالا.',
  'faq.answered': 'پرسش پاسخ داده‌شده در این صفحه',
  'faq.notFound': 'پاسخ خود را پیدا نکردید؟ با',
  'faq.call': 'تماس بگیرید.',
  'faq.empty': 'هنوز پرسشی در این صفحه ثبت نشده است. برای هر سوالی می‌توانید با پشتیبانی تماس بگیرید.',
  'faq.topics': 'موضوع‌ها',
  'faq.related': 'راهنماهای مرتبط',
  'faq.closingEyebrow': 'هنوز سوالی هست؟',
  'faq.closingTitle': 'بپرسید، پاسخ می‌دهیم',
  'faq.closingBody': 'اگر پاسخ پرسش شما در این صفحه نبود، از راه‌های ارتباطی زیر با پشتیبانی در تماس باشید.',
  'faq.topicsAria': 'فهرست موضوع‌ها',
  'about.pillar.fabricTitle': 'پارچه و دوخت',
  'about.pillar.fabricBody': 'پارچه‌های نرم و سبک با دوخت تمیز؛ بدون درز آزاردهنده و بدون برچسب اضافه روی پوست.',
  'about.pillar.sizeTitle': 'سایز درست',
  'about.pillar.sizeBody': 'برای هر محصول جدول سایز اختصاصی داریم تا انتخاب سایز حدس و گمان نباشد.',
  'about.pillar.packageTitle': 'بسته‌بندی محرمانه',
  'about.pillar.packageBody': 'سفارش شما در بسته‌بندی ساده و بدون نشان ارسال می‌شود؛ محتوای بسته روی آن نوشته نمی‌شود.',
  'about.pillar.supportTitle': 'کنار شما',
  'about.pillar.supportBody': 'قبل و بعد از خرید پاسخگوی پرسش‌های شما هستیم؛ از انتخاب سایز تا پیگیری سفارش.',
  'about.activeProducts': 'محصول فعال',
  'about.categories': 'دسته‌بندی',
  'about.reviews': 'دیدگاه ثبت‌شده',
  'about.shipping': 'ارسال',
  'about.returns': 'بازگشت کالا',
  'about.averageRating': 'میانگین امتیاز مشتریان',
  'about.learnMore': 'بیشتر بدانید',
  'about.start': 'شروع کنید',
  'about.closingBody': 'هر قطعه با همان دقتی انتخاب شده که در این صفحه خواندید.',
  'about.faq': 'سوالات متداول',
  'contact.shortcutFaq': 'پاسخ پرسش‌های پرتکرار درباره سفارش، سایز و ارسال.',
  'contact.shortcutShipping': 'زمان آماده‌سازی، هزینه ارسال و نحوه بسته‌بندی.',
  'contact.shortcutReturns': 'شرایط تعویض و بازگشت کالا را پیش از خرید بخوانید.',
  'contact.shortcutSize': 'جدول سایز و روش اندازه‌گیری صحیح.',
  'contact.phone': 'تماس تلفنی',
  'contact.email': 'ایمیل',
  'contact.call': 'شماره‌گیری',
  'contact.whatsappDisplay': 'گفت‌وگوی مستقیم',
  'contact.whatsappAction': 'شروع گفت‌وگو',
  'contact.telegramDisplay': 'پیام در تلگرام',
  'contact.sendMessage': 'ارسال پیام',
  'contact.emailAction': 'نوشتن ایمیل',
  'contact.instagramDisplay': 'جدیدترین‌ها را ببینید',
  'contact.follow': 'دنبال کنید',
  'contact.responder': 'پاسخگوی شما',
  'contact.heroLead': 'هر پرسشی درباره سایز، سفارش یا ارسال دارید، از نزدیک‌ترین راه زیر بپرسید.',
  'contact.address': 'نشانی',
  'contact.hours': 'ساعات پاسخگویی',
  'contact.afterHours': 'پیام‌های خارج از این ساعت را در نخستین فرصت کاری پاسخ می‌دهیم.',
  'contact.enamad': 'نماد اعتماد الکترونیکی',
  'contact.shortcutsEyebrow': 'شاید پاسخ اینجا باشد',
  'contact.shortcutsTitle': 'پیش از تماس، یک نگاه',
  'contact.yourOrder': 'سفارش شما',
  'later.title': 'سبد پرداخت بعدی',
  'later.draft': 'در حال آماده‌سازی',
  'later.open': 'منتظر تصمیم شما',
  'later.submitted': 'ثبت‌شده برای بازگشت',
  'later.converted': 'آماده پرداخت',
  'later.cancelled': 'لغوشده',
  'later.decisionSaved': 'تصمیم شما ثبت شد',
  'later.allReturned': 'همه کالاها برای بازگشت مشخص شدند و مبلغی برای پرداخت باقی نماند.',
  'later.expired': 'مهلت تصمیم‌گیری پایان یافته است',
  'later.expiredBody': 'برای تمدید مهلت یا ثبت تصمیم با پشتیبانی تماس بگیرید.',
  'later.deadline': 'مهلت ثبت تصمیم',
  'later.empty': 'سبد پرداخت بعدی شما خالی است',
  'later.disabled': 'این خدمت در حال حاضر فعال نیست',
  'later.emptyBody': 'از صفحه هر محصول، گزینه «افزودن به سبد پرداخت بعدی» را انتخاب کنید.',
  'later.backDashboard': 'بازگشت به پیشخوان',
  'later.history': 'سابقه سبدها',
  'later.cartPrefix': 'سبد شماره',
  'later.viewOrder': 'مشاهده سفارش',
  'later.itemsAria': 'کالاهای سبد پرداخت بعدی',
  'later.keep': 'نگه می‌دارم و پرداخت می‌کنم',
  'later.return': 'بازمی‌گردانم',
  'later.paymentAddress': 'پرداخت و نشانی',
  'later.keptItems': 'برای کالاهایی که نگه می‌دارید.',
  'later.savedAddress': 'نشانی ثبت‌شده',
  'later.addressRequired': 'پیش از نهایی‌کردن، از بخش «نشانی‌ها» یک نشانی ثبت کنید.',
  'later.noPayment': 'در حال حاضر روش پرداخت فعالی وجود ندارد. با پشتیبانی تماس بگیرید.',
  'later.finalAmount': 'مبلغ نهایی قابل پرداخت',
  'later.shipping': 'ارسال',
  'later.decisionSuffix': 'تصمیم ثبت شده',
  'later.returnSuffix': 'کالا برای بازگشت',
  'later.confirm': 'انتخاب‌ها را بررسی کرده‌ام و می‌دانم پس از ارسال، قابل تغییر نیستند.',
  'later.decisionFor': 'تصمیم برای',
  'later.of': 'از',
  'later.submitting': 'در حال ثبت…',
} as const

export type CopyKey = keyof typeof COPY_CATALOG
export type { ContentStyle } from '@/lib/content-style'

export async function getSiteContent() {
  const [copy, styles] = await Promise.all([
    getJson<Record<string, string>>('content', 'copy', {}),
    getJson<Record<string, ContentStyle>>('content', 'styles', {}),
  ])
  return {
    text: (key: CopyKey) => copy[key]?.trim() || COPY_CATALOG[key],
    style: (key: string) => styles[key] ?? {},
    styleClass: (key: string) => contentStyleClass(styles[key]),
    rawCopy: copy,
    rawStyles: styles,
    resolvedCopy: Object.fromEntries(
      Object.entries(COPY_CATALOG).map(([key, fallback]) => [key, copy[key]?.trim() || fallback]),
    ),
  }
}
