CREATE TABLE `get_later_carts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `created_by_admin_id` BIGINT UNSIGNED NOT NULL,
  `order_id` BIGINT UNSIGNED NULL,
  `status` ENUM('draft','open','submitted','converted','cancelled') NOT NULL DEFAULT 'draft',
  `admin_note` TEXT NULL,
  `customer_note` TEXT NULL,
  `expires_at` TIMESTAMP NULL,
  `opened_at` TIMESTAMP NULL,
  `submitted_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `get_later_order_unq` (`order_id`),
  KEY `get_later_user_status_idx` (`user_id`, `status`),
  KEY `get_later_status_created_idx` (`status`, `created_at`),
  CONSTRAINT `get_later_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `get_later_admin_fk` FOREIGN KEY (`created_by_admin_id`) REFERENCES `admin_users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `get_later_order_fk` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
--> statement-breakpoint
CREATE TABLE `get_later_items` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cart_id` BIGINT UNSIGNED NOT NULL,
  `variant_id` BIGINT UNSIGNED NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `product_name` VARCHAR(190) NOT NULL,
  `product_slug` VARCHAR(190) NOT NULL,
  `variant_label` VARCHAR(190) NULL,
  `sku` VARCHAR(64) NOT NULL,
  `image_path` VARCHAR(255) NULL,
  `original_price` BIGINT UNSIGNED NOT NULL,
  `unit_price` BIGINT UNSIGNED NOT NULL,
  `quantity` INT NOT NULL,
  `decision` ENUM('undecided','pay','return') NOT NULL DEFAULT 'undecided',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `get_later_item_unq` (`cart_id`, `variant_id`),
  KEY `get_later_items_cart_idx` (`cart_id`),
  CONSTRAINT `get_later_items_cart_fk` FOREIGN KEY (`cart_id`) REFERENCES `get_later_carts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `get_later_items_variant_fk` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `get_later_items_product_fk` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `get_later_items_quantity_chk` CHECK (`quantity` > 0),
  CONSTRAINT `get_later_items_price_chk` CHECK (`unit_price` <= `original_price`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
