'use server'

import { asc, eq } from 'drizzle-orm'
import { revalidatePath } from 'next/cache'
import { db } from '@/db'
import { shippingMethods } from '@/db/schema'
import * as audit from '@/lib/audit'
import { errors, fail, ok, type ActionResult } from '@/lib/errors'
import { requirePermission } from './auth'

function amount(value: string, label: string) { const n = Number(value); if (!Number.isSafeInteger(n) || n < 0 || n > 1_000_000_000) throw errors.validation(`${label} معتبر نیست.`); return n }
export async function saveShippingMethodAction(input: { id?: number; name: string; description: string; fee: string; freeThreshold: string; isEnabled: boolean; isDefault: boolean; sortOrder: string }): Promise<ActionResult<void>> { try { const admin = await requirePermission('settings.manage'); const name = input.name.trim(); if (name.length < 2 || name.length > 120) throw errors.validation('نام روش ارسال باید بین ۲ تا ۱۲۰ کاراکتر باشد.'); const fee = amount(input.fee, 'هزینه'); const freeThreshold = amount(input.freeThreshold, 'حد نصاب ارسال رایگان'); const sortOrder = amount(input.sortOrder, 'ترتیب'); if (input.description.length > 500) throw errors.validation('توضیح روش ارسال بیش از حد طولانی است.'); if (input.isDefault && !input.isEnabled) throw errors.validation('روش پیش‌فرض باید فعال باشد.'); if (input.isDefault) await db.update(shippingMethods).set({ isDefault: '0' }); const values = { name, description: input.description.trim() || null, fee, freeThreshold, isEnabled: input.isEnabled ? '1' as const : '0' as const, isDefault: input.isDefault ? '1' as const : '0' as const, sortOrder }; if (input.id) await db.update(shippingMethods).set(values).where(eq(shippingMethods.id, input.id)); else await db.insert(shippingMethods).values(values); const active = await db.select({ id: shippingMethods.id, isDefault: shippingMethods.isDefault }).from(shippingMethods).where(eq(shippingMethods.isEnabled, '1')).orderBy(asc(shippingMethods.sortOrder)).limit(1); if (!active[0]) throw errors.validation('حداقل یک روش ارسال فعال لازم است.'); const [defaultMethod] = await db.select({ id: shippingMethods.id }).from(shippingMethods).where(eq(shippingMethods.isDefault, '1')).limit(1); if (!defaultMethod) await db.update(shippingMethods).set({ isDefault: '1' }).where(eq(shippingMethods.id, active[0].id)); await audit.log({ actor: admin, action: 'settings.change', entityType: 'shipping_method', entityId: input.id ?? name }); revalidatePath('/checkout'); revalidatePath('/admin/settings'); return ok(undefined) } catch (error) { return fail(error, { action: 'saveShippingMethod' }) } }
export async function deleteShippingMethodAction(id: number): Promise<ActionResult<void>> { try { const admin = await requirePermission('settings.manage'); const active = await db.select({ id: shippingMethods.id }).from(shippingMethods).where(eq(shippingMethods.isEnabled, '1')); const [row] = await db.select().from(shippingMethods).where(eq(shippingMethods.id, id)).limit(1); if (!row) throw errors.notFound(); if (row.isEnabled === '1' && active.length <= 1) throw errors.validation('آخرین روش ارسال فعال قابل حذف نیست.'); await db.delete(shippingMethods).where(eq(shippingMethods.id, id)); if (row.isDefault === '1') { const [replacement] = await db.select().from(shippingMethods).where(eq(shippingMethods.isEnabled, '1')).orderBy(asc(shippingMethods.sortOrder)).limit(1); if (replacement) await db.update(shippingMethods).set({ isDefault: '1' }).where(eq(shippingMethods.id, replacement.id)); } await audit.log({ actor: admin, action: 'settings.change', entityType: 'shipping_method', entityId: id }); revalidatePath('/checkout'); revalidatePath('/admin/settings'); return ok(undefined) } catch (error) { return fail(error, { action: 'deleteShippingMethod', id }) } }
