import type { Metadata, Viewport } from 'next'
import { Lalezar, Vazirmatn } from 'next/font/google'

import { getNamespace } from '@/lib/settings'
import { getTheme, themeToCss } from '@/lib/theme'
import { getTypography, typographyToCss } from '@/lib/typography'
import { jsonLd, organizationSchema, siteUrl, websiteSchema } from '@/lib/seo'

import './globals.css'

/**
 * Both faces are downloaded and self-hosted at build time, then exposed as CSS
 * variables. The administrator's font choice is a runtime remap of
 * --font-heading / --font-body onto an already-loaded face — no extra request,
 * no flash, no rebuild. §8 / §49.
 */
const vazirmatn = Vazirmatn({
  subsets: ['arabic'],
  variable: '--font-vazirmatn',
  display: 'swap',
  weight: ['400', '500', '600', '700'],
  preload: true,
})

const lalezar = Lalezar({
  subsets: ['arabic'],
  variable: '--font-lalezar',
  display: 'swap',
  weight: '400',
  preload: true,
})

export async function generateMetadata(): Promise<Metadata> {
  const site = await getNamespace('site')
  const seo = await getNamespace('seo')

  const siteName = site.siteName || 'ارکید'

  return {
    metadataBase: new URL(siteUrl()),
    title: {
      default: seo.defaultTitle || `${siteName} — فروشگاه لباس زیر زنانه`,
      template: `%s${seo.titleSeparator || ' | '}${siteName}`,
    },
    description:
      seo.defaultDescription ||
      'فروشگاه اینترنتی ارکید؛ لباس زیر زنانه با کیفیت، طراحی ظریف و ارسال محرمانه به سراسر ایران.',
    applicationName: siteName,
    // The site is Persian-only; declaring it explicitly keeps search engines
    // from guessing from the markup.
    alternates: { canonical: '/' },
    icons: {
      // The full 3:1 lockup is illegible at 32px; icon.png is a blossom crop
      // generated by scripts/prepare-logo.mjs.
      icon: site.faviconPath ? `/api/media/${site.faviconPath}` : '/icon.png',
    },
    robots: { index: true, follow: true },
    openGraph: {
      type: 'website',
      locale: 'fa_IR',
      siteName,
      url: siteUrl(),
    },
    formatDetection: {
      // Persian addresses and postal codes get mangled by iOS autolinking.
      telephone: false,
      address: false,
    },
  }
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#EDE6DC',
  colorScheme: 'light',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const [theme, typography, enamad] = await Promise.all([
    getTheme(),
    getTypography(),
    getNamespace('enamad'),
  ])

  const [orgSchema, siteSchema] = await Promise.all([organizationSchema(), websiteSchema()])

  /*
   * Theme tokens are inlined rather than fetched.
   *
   * They change when an administrator saves, not when the code is built, so
   * they cannot be part of the compiled stylesheet — and a blocking request
   * for them would sit directly on the critical path and hurt LCP.
   */
  const themeCss = `:root{${themeToCss(theme)};${typographyToCss(typography)}}`

  return (
    <html lang="fa" dir="rtl" className={`${vazirmatn.variable} ${lalezar.variable}`}>
      <head>
        <style
          id="orchid-theme"
          // Values come from a validated hex/enum whitelist in lib/theme.ts —
          // an arbitrary string can never reach this.
          dangerouslySetInnerHTML={{ __html: themeCss }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonLd([orgSchema, siteSchema]) }}
        />
        {/* Enamad's verification meta tag, admin-configured. §51 */}
        {enamad.metaTag ? (
          <meta name="enamad" content={enamad.metaTag} />
        ) : null}
      </head>
      <body>
        <a href="#main" className="sr-only focus:not-sr-only">
          پرش به محتوای اصلی
        </a>
        {children}
      </body>
    </html>
  )
}
